name = "wannier"

[install]
completion = true
quiet = false
optimize = 2

# [sysimg]
# incremental = true
# filter_stdlibs = false

# [sysimg.precompile]
# # execution_file = ["deps/precompile.jl"]
# statements_file = ["deps/statements.jl"]

# [application]
# incremental = false
# filter_stdlibs = true
#
# [application.precompile]
# statements_file = ["deps/statements.jl"]
