[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Wannier = "2b19380a-1f7e-4d7d-b1b8-8aa60b3321c9"
WannierPlots = "aee37571-e66d-4c92-9c5d-c978af507da2"

[compat]
Documenter = "0.27.22"
JSServe = "1.2.8"
Literate = "2.13.4"
