[deps]
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
Wannier = "2b19380a-1f7e-4d7d-b1b8-8aa60b3321c9"
WannierIO = "cb1bc77f-5443-4951-af9f-05b616a3e422"
WannierPlots = "aee37571-e66d-4c92-9c5d-c978af507da2"

[compat]
Documenter = "0.27"
JSServe = "2"
Literate = "2"
LiveServer = "1.2.2"
PlotlyJS = "0.18"
WGLMakie = "0.8"
